%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming_BindingIterator
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_BINDINGITERATOR_HRL).
-define(COSNAMING_BINDINGITERATOR_HRL, true).




-endif.


