%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyComm
%% Source: /home/vagrant/build-dir_16-03-14_19-56-06/otp-support/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYCOMM_HRL).
-define(OE_COSNOTIFYCOMM_HRL, true).




-endif.


