%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_HRL).
-define(COSTIME_HRL, true).


-record('CosTime_TimeUnavailable', {'OE_ID'="IDL:omg.org/CosTime/TimeUnavailable:1.0"}).


-endif.


