%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm
%% Source: /home/vagrant/build-dir_16-03-14_19-10-08/otp-support/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_HRL).
-define(OE_COSEVENTCOMM_HRL, true).




-endif.


