%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cosEventApp
%% Source: /home/vagrant/build-dir_16-03-14_19-10-08/otp-support/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTAPP_HRL).
-define(OE_COSEVENTAPP_HRL, true).




-endif.


