%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TimeService
%% Source: /home/vagrant/build-dir_16-03-14_16-22-07/otp-support/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIMESERVICE_HRL).
-define(COSTIME_TIMESERVICE_HRL, true).




-endif.


