%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosProperty
%% Source: /home/vagrant/build-dir_16-03-14_16-22-07/otp-support/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSPROPERTY_HRL).
-define(OE_COSPROPERTY_HRL, true).




-endif.


