%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_RecoveryCoordinator
%% Source: /home/vagrant/build-dir_16-03-14_19-56-06/otp-support/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL).
-define(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL, true).




-endif.


