%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosFileTransfer_VirtualFileSystem_ContentList
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosFileTransfer_VirtualFileSystem_ContentList').
-ic_compiled("4_4").


-include("CosFileTransfer_VirtualFileSystem.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_long,0}.

%% returns id
id() -> "IDL:omg.org/CosFileTransfer/VirtualFileSystem/ContentList:1.0".

%% returns name
name() -> "CosFileTransfer_VirtualFileSystem_ContentList".



