%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PushConsumer
%% Source: /home/vagrant/build-dir_16-03-14_19-56-06/otp-support/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_PUSHCONSUMER_HRL, true).




-endif.


