%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_HRL).
-define(COSEVENTCHANNELADMIN_HRL, true).


-record('CosEventChannelAdmin_AlreadyConnected', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0"}).
-record('CosEventChannelAdmin_TypeError', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/TypeError:1.0"}).


-endif.


