%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventComm_Disconnected
%% Source: /home/vagrant/build-dir_16-03-14_16-22-07/otp-support/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventComm_Disconnected').
-ic_compiled("4_4").


-include("CosEventComm.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventComm/Disconnected:1.0","Disconnected",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosEventComm/Disconnected:1.0".

%% returns name
name() -> "CosEventComm_Disconnected".



