%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventHandler
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTHANDLER_HRL).
-define(COSTIMEREVENT_TIMEREVENTHANDLER_HRL, true).




-endif.


