%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_SupplierAdmin
%% Source: /home/vagrant/build-dir_16-03-14_16-22-07/otp-support/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_SUPPLIERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_SUPPLIERADMIN_HRL, true).




-endif.


