%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicHazard
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicHazard').
-ic_compiled("4_4").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicHazard:1.0",
                   "HeuristicHazard",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicHazard:1.0".

%% returns name
name() -> "CosTransactions_HeuristicHazard".



