%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventDomainAdmin_EventDomain
%% Source: /home/vagrant/build-dir_16-03-14_19-10-08/otp-support/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTDOMAINADMIN_EVENTDOMAIN_HRL).
-define(COSEVENTDOMAINADMIN_EVENTDOMAIN_HRL, true).




-endif.


