%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Resource
%% Source: /home/vagrant/build-dir_16-03-14_16-22-07/otp-support/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RESOURCE_HRL).
-define(COSTRANSACTIONS_RESOURCE_HRL, true).




-endif.


