%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP
%% Source: /home/vagrant/build-dir_16-03-14_16-22-07/otp-support/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_HRL).
-define(ETRAP_HRL, true).




-endif.


