%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertiesIterator
%% Source: /home/vagrant/build-dir_16-03-14_19-56-06/otp-support/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL).
-define(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL, true).




-endif.


