%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_SequencePushSupplier
%% Source: /home/vagrant/build-dir_16-03-14_19-10-08/otp-support/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_SEQUENCEPUSHSUPPLIER_HRL).
-define(COSNOTIFYCOMM_SEQUENCEPUSHSUPPLIER_HRL, true).




-endif.


