%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullConsumer
%% Source: /home/vagrant/build-dir_16-03-14_19-56-06/otp-support/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL, true).




-endif.


