%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_StructuredProxyPullSupplier
%% Source: /private/tmp/erlang20150820-34163-1k9di6g/otp-OTP-18.0.3/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_STRUCTUREDPROXYPULLSUPPLIER_HRL).
-define(COSNOTIFYCHANNELADMIN_STRUCTUREDPROXYPULLSUPPLIER_HRL, true).




-endif.


